### ISSUE TITLE
fatal: syscall getrandom (#278) unimplemented.

### ISSUE THREAD

**Issue by sjcjjcjssdssjc** [cucapra/gem5-mesh#121]
![image](https://github.com/cucapra/gem5-mesh/assets/38655779/308d7db7-40ad-467c-b0a3-f6a2e316acdb)
I was running stencil program with the newest RISCV gnu toolchain but the gem5 simulation failed with syscall not supported.

**Comment by sjcjjcjssdssjc** [comment]
fatal: syscall getrandom (#278) unimplemented.
Memory Usage: 731536 KBytes
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/pedestrian/gem5-mesh/scripts-phil/eval/run_sim.py", line 228, in pack_and_run
    return run_prog(numCpus, use_vec, use_sps, program, argv, extra_info)
  File "/home/pedestrian/gem5-mesh/scripts-phil/eval/run_sim.py", line 88, in run_prog
    result = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '../../build/RVSP/gem5.opt --remote-gdb-port=0 -d ./example/stencil-vec1-4_4_-cols5522-rows60 ../../configs/phil/brg_hammerblade.py --cmd=../../programs-spad/stencil/stencil --options="5522 60" --num-cpus=64 --vector' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pedestrian/gem5-mesh/scripts-phil/eval/run_sim.py", line 254, in <module>
    if (p.get() == False):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
subprocess.CalledProcessError: Command '../../build/RVSP/gem5.opt --remote-gdb-port=0 -d ./example/stencil-vec1-4_4_-cols5522-rows60 ../../configs/phil/brg_hammerblade.py --cmd=../../programs-spad/stencil/stencil --options="5522 60" --num-cpus=64 --vector' returned non-zero exit status 1.
